# Generated by Django 5.1.6 on 2025-04-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_lasst_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='ShopBE_cust_last_na_c8022c_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
