# Generated by Django 5.1.6 on 2025-04-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_customer_shopbe_cust_last_na_c8022c_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collecction',
            new_name='Collection',
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='iventory',
            new_name='inventory',
        ),
    ]
