# Generated by Django 5.1.6 on 2025-04-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_collecction_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
